name: Tests

on:
  workflow_dispatch:
  #push:
  #  tags: v*.*.*

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: autotest
    steps:
      - name: Start
        run: |
          cd C:\actions-runner\autotest\
          .\AutomaticTesting.exe -all

