name: Build all Apps

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'forkflow/build_all'

jobs:
  
    
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare building
        uses: oxr463/setup-cordova@0.0.3
        with:
          exec: |
            npm i
            npm run minimize:cordova
            cd ./cordova
            npm i
      - name: Prepare configuration
        uses: oxr463/setup-cordova@0.0.3
        with:
          exec: |
            cd ./cordova
            echo -n "${{ secrets.ANDROID_SECRET_KEY }}" | base64 -d > key
            echo -n "${{ secrets.ANDROID_BUILD_CONF }}" | base64 -d > build.json
            echo -n "${{ secrets.ANDROID_FIREBASE_CONF }}" | base64 -d > google-services.json
      - name: Building
        uses: oxr463/setup-cordova@0.0.3
        with:
          exec: |
            cd ./cordova
            chmod -R 777 $ANDROID_HOME
            npm run android-add
            npm run android-build
            cd ./platforms/android/app/build/outputs/apk/release
            ls -lh
            mv app-release.apk Bastyon.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: ./cordova/platforms/android/app/build/outputs/apk/release/Bastyon.apk
