name: Build all Apps

on:
  workflow_dispatch:
  push:
    branches:
      - 'forkflow/build_all'

jobs:
  
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare for app notarization
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
      - name: Prepare building
        run: |
          npm i
          npm run dev:bastyon
      - name: Building
        run: |
          npm run distm
          ls -lh ./dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: ./dist/BastyonSetup.dmg
        
  build-unix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare building
        run: |
          npm i
          npm run dev:bastyon
      - name: Building
        run: |
          npm run distl
          ls -lh ./dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: unix
          path: |
            ./dist/BastyonSetup.deb
            ./dist/Bastyon.AppImage
    
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare building
        run: |
          npm i
          npm run dev:bastyon
      - name: Building
        run: |
          npm run dist
          ls .\dist\
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./dist/BastyonSetup.exe

    
 build-android:
   runs-on: ubuntu-latest
   steps:
     - name: Check out Git repository
       uses: actions/checkout@v1
     - name: Install Node.js, NPM and Yarn
       uses: actions/setup-node@v1
       with:
         node-version: 14
     - name: Prepare building
       run: |
         npm i
         npm run minimize:cordova
         cd ./cordova
         npm i

       # TODO:
       # - Copy keystore file (./cordova or any other, but path is provided in build configuration)
       # - Copy build configuration (./cordova)
       # - Copy Firebase configuration (./cordova/platforms/android/app)

     - name: Building
       run: |
         cd ./cordova
         npm run android-add
         npm run android-build
         cd ./platforms/android/app/build/outputs/apk/release
         ls
         mv app-release.apk Bastyon.apk
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
         name: android
         path: ./cordova/platforms/android/app/build/outputs/apk/release/Bastyon.apk
