name: Build all Apps

on:
  workflow_dispatch:
  push:
    branches:
      - 'forkflow/build_all'

jobs:
  
    
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Check out Git repository
        uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Cordova
        run: |
          npm i -g cordova@10
          cordova --version
      - name: Prepare building
        run: |
          npm i
          npm run minimize:cordova
          cd ./cordova
          npm i
      - name: Prepare configuration
        run: |
          cd ./cordova
          echo -n "${{ secrets.ANDROID_SECRET_KEY }}" | base64 -d > cert.keystore
          echo -n "${{ secrets.ANDROID_BUILD_CONF }}" | base64 -d > build.json
          echo -n "${{ secrets.ANDROID_FIREBASE_CONF }}" | base64 -d > google-services.json
          ls -l cert.keystore
          ls -l build.json
      - name: Fixing Android Build Tool Issue
        run: |
            cd $ANDROID_HOME/build-tools/33.0.0
            mv d8 dx
            cd lib
            mv d8.jar dx.jar
      - name: Configure Cordova Plugins
        run: |
          cd ./cordova
          npm run android-add
      - name: Building
        run: |
          cd ./cordova
          npm run android-build
      - name: Rename apk binary
        run: |
          cd ./cordova/platforms/android/app/build/outputs/apk/release
          ls -lh
          mv app-release.apk Bastyon.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: ./cordova/platforms/android/app/build/outputs/apk/release/Bastyon.apk
