name: Cordova Install

on:
  workflow_dispatch:
  push:
    branches:
      - 'forkflow/build_all'

jobs:
  
    
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Cordova
        run: npm i -g cordova@10
      - name: check cordova
        run: cordova --version
