name: Deploy Web

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Prepare
        run: |
          npm i
          npm run build:proxy16
          npm run minimize:lotos -- -sha=${{ github.sha }}
        
      - name: Prepare archive
        run: |
          mkdir /tmp/lotos
          rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /tmp/lotos/
          tar czf /tmp/lotos.tgz -C /tmp/lotos .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lotos.tgz
          path: /tmp/lotos.tgz

  deploy:
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ btio1, btio2, btio3 ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lotos.tgz
      - name: Install
        run: /data/install_web.sh
      - name: Reset nginx cache
        run: /data/reset_cache.sh
        shell: bash
