name: Deploy to test.pocketnet.app

on:
  workflow_dispatch:
  push:
    tags: v*.*.*

jobs:
  build:
  
    if: github.event.base_ref == 'refs/heads/release'
    
    runs-on: gui 

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare
        run: |
          npm i
          npm run minimize:bastyon:test

      - name: Copy to dest dir
        run: rsync -ah --exclude={'.git','.gitignore','.github','package.json','node_modules','.well-known','assets','proxy16','cordova','res','build'} ./ /docker/gui/
